### ISSUE TITLE
Every element of svg is focusable by default (web, chrome)

### ISSUE THREAD

**Issue by Dammic** [react-native-svg/react-native-svg#1471]
# Bug
Right now, every single element of SVG is focusable by default. This can be seen directly on the demo from readme:
https://snack.expo.io/@msand/react-native-svg-example

I was able to make it work locally, but I had to add 'tabIndex="-1" to every single svg element, and that prevented focus.

## Environment info

Library version: 12.1.0

## Steps To Reproduce

1) open it in chrome (my version is 84.0.4147.89)
2) wait for the svgs to load, and then try to 'tab' through them - you will see that each element of single svg is focusable (best seen on the 'G' or 'Clipping' example
![Zaznaczenie_157](https://user-images.githubusercontent.com/18100361/95204780-d6a4e200-07e4-11eb-8670-73eb56d5128a.png)

Describe what you expected to happen:

1) None of the svgs are explicitly focusable (like on firefox)

**Comment by jondkoon** [comment]
I was experiencing this as well and was able to track the source of the issue although I don't know what the right solve is.

Apparently an SVG is considered focusable by the browser if it has certain event handlers attached: https://www.w3.org/TR/SVGTiny12/interact.html#focus

It looks like the `WebShape` class which all svg components inherit from when rendered on the web includes the `SvgTouchableMixin`: https://github.com/react-native-svg/react-native-svg/blob/develop/src/lib/SvgTouchableMixin.ts

The `TouchableMixin` implemented in `react-native-web` adds a blur event listener on componentDidMount: https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/Touchable/index.js#L381

I discovered this using `getEventListeners()` on an svg and tracing the blur listener.
You can verify the browser behavior by adding a blur listener to an otherwise non-focusable svg using the dev tools and observing that you can tab to it.

One potential solution would be to conditionally include `SvgTouchableMixin`: https://github.com/react-native-svg/react-native-svg/blob/develop/src/lib/SvgTouchableMixin.ts based on the props passed.

There is already some similar code here that checks `hasTouchableProperty`: https://github.com/react-native-svg/react-native-svg/blob/develop/src/ReactNativeSVG.web.ts#L97

**Comment by minheq** [comment]
i don't expect in my projects to be using any advanced features for react-native-svg other than just displaying svgs. for that, i am working around this issue by re-exporting HTML svg elements instead. here for reference:

```tsx
// svg.tsx
export * from 'react-native-svg';
import Svg from 'react-native-svg';

export default Svg;
```

```tsx
// svg.web.tsx
import React from 'react';

export function Circle(props: React.SVGProps<SVGCircleElement>): JSX.Element {
  return <circle {...props} />;
}

export function ClipPath(
  props: React.SVGProps<SVGClipPathElement>,
): JSX.Element {
  return <clipPath {...props} />;
}

export function Defs(props: React.SVGProps<SVGDefsElement>): JSX.Element {
  return <defs {...props} />;
}

export function Ellipse(props: React.SVGProps<SVGEllipseElement>): JSX.Element {
  return <ellipse {...props} />;
}

export function G(props: React.SVGProps<SVGGElement>): JSX.Element {
  return <g {...props} />;
}

export function Image(props: React.SVGProps<SVGImageElement>): JSX.Element {
  return <image {...props} />;
}

export function Line(props: React.SVGProps<SVGLineElement>): JSX.Element {
  return <line {...props} />;
}

export function LinearGradient(
  props: React.SVGProps<SVGLinearGradientElement>,
): JSX.Element {
  return <linearGradient {...props} />;
}

export function Path(props: React.SVGProps<SVGPathElement>): JSX.Element {
  return <path {...props} />;
}

export function Polygon(props: React.SVGProps<SVGPolygonElement>): JSX.Element {
  return <polygon {...props} />;
}

export function Polyline(
  props: React.SVGProps<SVGPolylineElement>,
): JSX.Element {
  return <polyline {...props} />;
}

export function RadialGradient(
  props: React.SVGProps<SVGRadialGradientElement>,
): JSX.Element {
  return <radialGradient {...props} />;
}

export function Rect(props: React.SVGProps<SVGRectElement>): JSX.Element {
  return <rect {...props} />;
}

export function Stop(props: React.SVGProps<SVGStopElement>): JSX.Element {
  return <stop {...props} />;
}

export function Svg(props: React.SVGProps<SVGSVGElement>): JSX.Element {
  return <svg {...props} />;
}

export function Symbol(props: React.SVGProps<SVGSymbolElement>): JSX.Element {
  return <symbol {...props} />;
}

export function Text(props: React.SVGProps<SVGTextElement>): JSX.Element {
  return <text {...props} />;
}

export function TSpan(props: React.SVGProps<SVGTSpanElement>): JSX.Element {
  return <tspan {...props} />;
}

export function TextPath(
  props: React.SVGProps<SVGTextPathElement>,
): JSX.Element {
  return <textPath {...props} />;
}

export function Use(props: React.SVGProps<SVGUseElement>): JSX.Element {
  return <use {...props} />;
}

export function Mask(props: React.SVGProps<SVGMaskElement>): JSX.Element {
  return <mask {...props} />;
}

export function ForeignObject(
  props: React.SVGProps<SVGForeignObjectElement>,
): JSX.Element {
  return <foreignObject {...props} />;
}

export function Marker(props: React.SVGProps<SVGMarkerElement>): JSX.Element {
  return <marker {...props} />;
}

export function Pattern(props: React.SVGProps<SVGPatternElement>): JSX.Element {
  return <pattern {...props} />;
}

export default Svg;
```

**Comment by jondkoon** [comment]
@minheq I have done something similar with `svgr` to work around the issue. I am generating `*.native.js` components that use `react-native-svg` and then I generate `*.js` components for use with web.

In the case where you aren't using `react-native-svg` specific apis and are just trying to render an SVG where you can change the color I think this is a superior approach anyway. That being said I think `react-native-svg` is trying to do this internally - it just needs to be patched a bit.

**Comment by jpaas** [comment]
Any ideas on how to proceed? Adding `tabindex={-1}` to every Svg element is a bit tedious and it also causes Typescript errors.

**Comment by intergalacticspacehighway** [comment]
@jondkoon thanks for the analysis, it really helped in implementing the fix. Can you verify the changes?
https://github.com/react-native-svg/react-native-svg/pull/1585

**Comment by efoken** [comment]
Will this be merged soon? We really need this fix here, because currently keyboard navigation is real pain 😅
