### ISSUE TITLE
Animated.createAnimatedComponent(Stop) throws error

### ISSUE THREAD

**Issue by param-finder** [react-native-svg/react-native-svg#1695]
# Bug
```
import Svg, { Defs, LinearGradient, Stop, Path } from 'react-native-svg';
const AnimatedStop = Animated.createAnimatedComponent(Stop);
```
throws

```
ERROR  Invariant Violation: Unable to locate attached view in the native tree

This error is located at:
    in PathIcon (at DepositWithdraw.tsx:18)
```

#### Unexpected behavior
"react-native-svg": "12.2.0",
"react-native": "0.66.4",

## Environment info

```
System:
    OS: macOS 12.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 240.96 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8092744
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.4 => 0.66.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

![Simulator Screen Shot - iPhone 13 - 2022-02-15 at 16 35 44](https://user-images.githubusercontent.com/92723723/154106643-ef235de1-8f44-4931-999d-5ee0a0ca5a60.png)

**Comment by jaraujocds** [comment]
Same here, did you solve it?

**Comment by param-finder** [comment]
Nope

**Comment by WoLewicki** [comment]
`Stop` element does not render anything (https://github.com/react-native-svg/react-native-svg/blob/d859083687fe44f3939b1868f5688306bee35651/src/elements/Stop.tsx#L19), but is used in its parent: https://github.com/react-native-svg/react-native-svg/blob/d859083687fe44f3939b1868f5688306bee35651/src/lib/extract/extractGradient.ts#L64. Therefore, you cannot `createAnimatedComponent` with it. In order for it to work, you would have to implement some hacky solution with providing the extracted values directly to `RNSVGLinearGradient` component instead of using `Stop` component for it. Can I close this issue then?

**Comment by Titozzz** [comment]
I can confirm it's possible to animate the native gradient prop directly on LinearGradient. Thanks @WoLewicki for the idea, works great.

**Comment by lachlanmcbride** [comment]
> I can confirm it's possible to animate the native gradient prop directly on LinearGradient. Thanks @WoLewicki for the idea, works great.

Do you have an example of how to extract the values onto `RNSVGLinearGradient`? I'm unable to get this to work.
